---
Name: silverstripe-algolia
---
SilverStripe\CMS\Model\SiteTree:
  field_to_reindex_children: "URLSegment"
  children_method_for_index: "AllChildren"
  extensions:
    - Wilr\SilverStripe\Algolia\Extensions\AlgoliaObjectExtension
SilverStripe\Subsites\Pages\SubsitesVirtualPage:
  extensions:
    - Wilr\SilverStripe\Algolia\Extensions\SubsitesVirtualPageExtension
SilverStripe\CMS\Model\VirtualPage:
  extensions:
    - Wilr\SilverStripe\Algolia\Extensions\VirtualPageExtension
  non_virtual_fields:
    - AlgoliaUUID
    - AlgoliaIndexed
    - AlgoliaError
