---
Name: silverstripe-algolia
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
   - Wilr\SilverStripe\Algolia\Extensions\AlgoliaSiteConfigExtension

SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - Wilr\SilverStripe\Algolia\Extensions\AlgoliaControllerExtension

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Wilr\SilverStripe\Algolia\Extensions\AlgoliaObjectExtension
